export const NEW_ACCOUNT = "NEW_ACCOUNT";
export const FETCH_ACCOUNT_COMPLETE = "FETCH_ACCOUNT_COMPLETE";
export const FETCH_ACCOUNTS_COMPLETE = "FETCH_ACCOUNTS_COMPLETE";
export const EDIT_ACCOUNT = "EDIT_ACCOUNT";
export const CLEAR_ACCOUNT = "CLEAR_ACCOUNT";

export const NEW_SUBSCRIPTION = "NEW_SUBSCRIPTION";
export const FETCH_SUBSCRIPTION_COMPLETE = "FETCH_SUBSCRIPTION_COMPLETE";
export const FETCH_SUBSCRIPTIONS_COMPLETE = "FETCH_SUBSCRIPTIONS_COMPLETE";
export const EDIT_SUBSCRIPTION = "EDIT_SUBSCRIPTION";
export const CLEAR_SUBSCRIPTION = "CLEAR_SUBSCRIPTION";

export const NEW_INVOICE = "NEW_INVOICE";
export const FETCH_INVOICE_COMPLETE = "FETCH_INVOICE_COMPLETE";
export const FETCH_INVOICES_COMPLETE = "FETCH_INVOICES_COMPLETE";
export const EDIT_INVOICE = "EDIT_INVOICE";
export const CLEAR_INVOICE = "CLEAR_INVOICE";

export const NEW_TRANSACTION = "NEW_TRANSACTION";
export const FETCH_TRANSACTION_COMPLETE = "FETCH_TRANSACTION_COMPLETE";
export const FETCH_TRANSACTIONS_COMPLETE = "FETCH_TRANSACTIONS_COMPLETE";
export const EDIT_TRANSACTION = "EDIT_TRANSACTION";
export const CLEAR_TRANSACTION = "CLEAR_TRANSACTION";

export const NEW_PLAN = "NEW_PLAN";
export const FETCH_PLAN_COMPLETE = "FETCH_PLAN_COMPLETE";
export const FETCH_PLANS_COMPLETE = "FETCH_PLANS_COMPLETE";
export const EDIT_PLAN = "EDIT_PLAN";
export const CLEAR_PLAN = "CLEAR_PLAN";

export const FETCH_ANALYTICS_COMPLETE = "FETCH_ANALYTICS_COMPLETE";

export const CLOSE_DIALOG = "CLOSE_DIALOG";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";
