import React from "react";
import Button from "@material-ui/core/Button";
import Dialog from "@material-ui/core/Dialog";
import DialogActions from "@material-ui/core/DialogActions";
import DialogContent from "@material-ui/core/DialogContent";
import DialogTitle from "@material-ui/core/DialogTitle";
import Icon from "@material-ui/core/Icon";
import { makeStyles } from "@material-ui/styles";
import RecordForm from "../RecordForm";
import * as actions from "../../redux/actions";
import { connect } from "react-redux";

const useStyles = makeStyles((theme) => ({
	extraAction: {
		textTransform: "none",
	},
	dialogAction: {
		textTransform: "none",
	},
	mainMore: {
		marginLeft: "auto",
		marginRight: "auto",
		maxWidth: 800,
	},
	mainLess: {
		marginLeft: "auto",
		marginRight: "auto",
		maxWidth: 500,
	},
	actions: {
		width: "100%",
	},
	extraActions: {
		width: "50%",
		display: "flex",
	},
	dialogActions: {
		width: "50%",
		display: "flex",
		flexDirection: "row-reverse",
	},
}));

const groups = [
	{
		label: "Basic",
		children: [
			{
				label: "User Name",
				identifier: "userName",
				type: "text_field",
				required: false,
				readOnly: false,
				quickAdd: true,
				unique: false,
				hidden: false,
				tooltip: "The user name of the account.",
				multipleValues: false,
				defaultValue: "",
			},
			{
				label: "First Name",
				identifier: "firstName",
				type: "text_field",
				required: true,
				readOnly: false,
				quickAdd: true,
				unique: false,
				hidden: false,
				tooltip: "The first name of the account.",
				multipleValues: false,
				defaultValue: "",
			},
			{
				label: "Last Name",
				identifier: "lastName",
				type: "text_field",
				required: true,
				readOnly: false,
				quickAdd: true,
				unique: false,
				hidden: false,
				tooltip: "The last name of the account.",
				multipleValues: false,
				defaultValue: "",
			},
			{
				label: "Email Address",
				identifier: "emailAddress",
				type: "email_address",
				required: false,
				readOnly: false,
				quickAdd: true,
				unique: false,
				hidden: false,
				tooltip: "The email address of the account.",
				multipleValues: true,
				defaultValue: "",
			},
			{
				label: "Phone Number",
				identifier: "phoneNumber",
				type: "phone_number",
				required: false,
				readOnly: false,
				quickAdd: true,
				unique: false,
				hidden: false,
				tooltip: "The phone number of the account.",
				multipleValues: true,
				defaultValue: "",
			},
			{
				label: "Address Line 1",
				identifier: "addressLine1",
				type: "text_field",
				required: false,
				readOnly: false,
				quickAdd: false,
				unique: false,
				hidden: false,
				tooltip: "The first line of address.",
				multipleValues: false,
				defaultValue: "",
			},
			{
				label: "Address Line 2",
				identifier: "addressLine2",
				type: "text_field",
				required: false,
				readOnly: false,
				quickAdd: false,
				unique: false,
				hidden: false,
				tooltip: "The first line of address.",
				multipleValues: false,
				defaultValue: "",
			},
			{
				label: "City",
				identifier: "city",
				type: "text_field",
				required: false,
				readOnly: false,
				quickAdd: false,
				unique: false,
				hidden: false,
				tooltip: "The city.",
				multipleValues: false,
				defaultValue: "",
			},
			{
				label: "State",
				identifier: "state",
				type: "text_field",
				required: false,
				readOnly: false,
				quickAdd: false,
				unique: false,
				hidden: false,
				tooltip: "The state where the customer resides.",
				multipleValues: false,
				defaultValue: "",
			},
			{
				label: "Country",
				identifier: "country",
				type: "text_field",
				required: false,
				readOnly: false,
				quickAdd: false,
				unique: false,
				hidden: false,
				tooltip: "The country where the customer resides.",
				multipleValues: false,
				defaultValue: "",
			},
			{
				label: "Zip Code",
				identifier: "zipCode",
				type: "text_field",
				required: false,
				readOnly: false,
				quickAdd: false,
				unique: false,
				hidden: false,
				tooltip:
					"The zip code of the location where the customer resides.",
				multipleValues: false,
				defaultValue: "",
			},
		],
	},
	{
		label: "Organization",
		children: [
			{
				label: "Name",
				identifier: "companyName",
				type: "text_field",
				required: false,
				readOnly: false,
				quickAdd: false,
				unique: false,
				hidden: false,
				tooltip: "The last name of the account.",
				multipleValues: false,
				defaultValue: "",
			},
			{
				label: "Position",
				id: "position",
				name: "position",
				type: "text",
				required: false,
				readOnly: false,
				quickAdd: false,
				unique: false,
				hidden: false,
				tooltip: "The position of the account in the organization.",
				multipleValues: false,
				defaultValue: "",
			},
			{
				label: "Email Address",
				identifier: "companyEmailAddress",
				type: "email_address",
				required: false,
				readOnly: false,
				quickAdd: false,
				unique: false,
				hidden: false,
				tooltip: "The email address of the account.",
				multipleValues: true,
				defaultValue: "",
			},
			{
				label: "Phone Number",
				identifier: "companyPhoneNumber",
				type: "phone_number",
				required: false,
				readOnly: false,
				quickAdd: false,
				unique: false,
				hidden: false,
				tooltip: "The phone number of the account.",
				multipleValues: true,
				defaultValue: "",
			},
		],
	},
];
